services:
  mysql:
    image: mysql:8
    container_name: mysql-contatos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contatos_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
